name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  verify:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ "python" ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
    - name: Run tests with pytest
      run: |
        uv run pytest
